pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '20', daysToKeepStr: '5'))
    }
    environment {
                SERVICE_CREDS = credentials('LocalMySQL') //DB connection credentials
    }
    stages {
        stage('checkout') {
            steps {
                script {
                    properties([pipelineTriggers([pollSCM('*/30 * * * *')])])
                }
                git 'https://github.com/GalBoyanjo/DevOpsExperts.git'
            }
        }
        stage('Run rest_app') {
            steps {
                script {
                    if (checkOs() == 'Windows') {
                        bat 'start /min python project/rest_app.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    } else {
                        sh 'nohup python project/rest_app.py & %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    }
                }
            }
        }
        stage('Run web_app') {
            steps {
                script {
                    if (checkOs() == 'Windows') {
                        bat 'start /min python project/web_app.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    } else {
                        sh 'nohup python project/web_app.py & %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    }
                }
            }
        }
        stage('Run backend_testing') {
            steps {
                script {
                    if (checkOs() == 'Windows') {
                        bat 'python project/backend_testing.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    } else {
                        sh 'python project/backend_testing.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    }
                }
            }
        }
        stage('Run frontend_testing') {
            steps {
                script {
                    if (checkOs() == 'Windows') {
                        bat 'python project/frontend_testing.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    } else {
                        sh 'python project/frontend_testing.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    }
                }
            }
        }
        stage('Run combined_testing') {
            steps {
                script {
                    if (checkOs() == 'Windows') {
                        bat 'python project/combined_testing.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    } else {
                        sh 'python project/combined_testing.py %SERVICE_CREDS_USR% %SERVICE_CREDS_PSW%'
                    }
                }
            }
        }
        stage('Run clean_environment') {
            steps {
                script {
                    if (checkOs() == 'Windows') {
                        bat 'python project/clean_environment.py'
                    } else {
                        sh 'python project/clean_environment.py'
                    }
                }
            }
        }
    }
    post{
        failure {
            emailext to: "gal.boyanjo@qmarkets.net",
            subject: "jenkins build:${currentBuild.currentResult}: ${env.JOB_NAME}",
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME}\nMore Info can be found here: ${env.BUILD_URL}",
            attachLog: true
        }
    }
}

def checkOs(){
    if (isUnix()) {
        def uname = sh script: 'uname', returnStdout: true
        if (uname.startsWith("Darwin")) {
            return "Macos"
        }
        else {
            return "Linux"
        }
    }
    else {
        return "Windows"
    }
}